sudo: false
language: cpp
dist: xenial
os:
- linux
- osx
compiler:
- gcc
- clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CC=gcc-7 ;
    export CXX=g++-7 ;
  fi
  wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-$OS.sh
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda config --set always_yes yes --set changeps1 no
  conda config --add channels conda-forge
  conda update -q conda
  conda install -q conda-build
  conda create -q -n test-environment python=$CONDA
  source activate test-environment
script:
- pip install .