name: Test C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  test_cpp:
    name: build (${{ matrix.os }}, C++)
    
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run:  |
        source ${CONDA}/conda activate
        conda install -c conda-forge benchmark catch2 eigen pybind11
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DBUILD_PYTHON_MODULE=OFF

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      if: ${{ !startsWith(runner.os, 'Windows') }}
      working-directory: ${{runner.workspace}}/build
      run: ./tests

    - name: Test
      if: startsWith(runner.os, 'Windows')
      working-directory: ${{runner.workspace}}/build
      run: ${{runner.workspace}}\build\Release\tests.exe
      shell: cmd
